Mrp 2020
danielhers/tupa pull request #106
Opened 2020-08-10 09:28 UTC by OfirArviv

2020-08-10 12:02 UTC, danielhers commented
Thanks, very helpful. Any script updates for training / prediction?

2020-08-10 12:04 UTC, OfirArviv commented
> 
> 
> Thanks, very helpful. Any script updates for training / prediction?

It the same really. Don't think there are any changes from the standard ones.
For example for amr:

python -m tupa --seed $RANDOM --cores=16 --use-bert --dynet-gpu --pytorch-gpu --no-validate-oracle --save-every=50000 \
    -t ../mrp/2020/cf/training/amr.mrp -d ../mrp/2020/cf/validation/amr.mrp \
    --conllu ../mrp/2020/cf/companion/udpipe.mrp --alignment ../mrp/2020/cf/companion/isi.mrp -m models/amr -v

2020-09-04 07:06 UTC, danielhers requested changes

2020-09-04 07:06 UTC, danielhers commented on tupa/oracle.py
> +            return
Should be `return None` to be more explicit.

2020-09-12 16:39 UTC, OfirArviv commented on tupa/config.py
> +EDGE_LABELS_NUM = {"amr": 141, "dm": 59, "psd": 90, "eds": 10, "ucca": 15, "ptg": 150}
The default values are enough

2020-09-12 16:40 UTC, OfirArviv commented on tupa/states/ref_graph.py
> +    edges_tuple = list(map(lambda x: (x.src, x.tgt), graph.edges))
habit from typescript :) changed it

2020-09-12 20:28 UTC, OfirArviv commented
Still failing due to EDS. I'll check later why

2020-10-13 11:07 UTC, danielhers commented
Hey @OfirArviv , when you get a chance, could you fix the code to make this PR pass?
https://travis-ci.com/github/danielhers/tupa/jobs/384233352#L806
For EDS, the oracle returns `REDUCE` for an unanchored `poss` node, which violates the constraints; but I think this node is just unanchored in the gold graph so the constraints should allow reducing it.

2020-10-13 19:26 UTC, OfirArviv commented
> 
> 
> Hey @OfirArviv , when you get a chance, could you fix the code to make this PR pass?
> https://travis-ci.com/github/danielhers/tupa/jobs/384233352#L806
> For EDS, the oracle returns `REDUCE` for an unanchored `poss` node, which violates the constraints; but I think this node is just unanchored in the gold graph so the constraints should allow reducing it.

Sorry. With all the pressure forgot about it. The question is, why it broke? We didn't change anything related to EDS as far as I can see. Did something changed in the build?

2020-10-14 08:13 UTC, danielhers commented
You are right. I finally figured out it's due to a bug in mtool: cfmrp/mtool#84.

2020-10-14 08:13 UTC, merged